ARG NODE_VERSION=14.19

# Dev
FROM node:${NODE_VERSION}-alpine As development
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 5000
RUN npm run build

# Prod
FROM node:${NODE_VERSION}-alpine as production
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
WORKDIR /app
COPY package*.json ./
RUN npm install --only=prod

COPY --from=development /app/dist ./dist
EXPOSE 5000
CMD [ "sh", "-c", "npm run start:prod"]
